name: CI

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Copy environment file
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Instantiate database
        run: |
          touch storage/app/database.sqlite
          php artisan migrate
      - name: Run unit/feature tests
        run: vendor/bin/phpunit